import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalState from '@/context/index'
import NextAuthProvider from '@/auth-provider/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netflix Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <GlobalState>{children}</GlobalState>
        </NextAuthProvider>
      </body>
    </html>
  )
}
